マジックナンバーを定数に変更しました。
takuya-lucky/lamp_practice pull request #20
Opened 2020-01-02 03:02 UTC by takuya-lucky

関数上及びhtml上にあった数字を全て定数に変更しました。
定数名などの命名にわかりづらいところがありましたら、ご指摘ください。
また、不要なものまで、定数化している恐れもありますので、お手数おかけしますが、確認をお願いいたします。

2020-01-03 03:00 UTC, thisprodigiousgeek commented on www/conf/const.php
> +define('DEFAULT_PRICE', 0);
0からスタートで読み取れる箇所ですので、こちらは定数化は不要そうですね！

2020-01-03 03:00 UTC, thisprodigiousgeek commented on www/conf/const.php
> +define('DEFAULT_CART_AMOUNT', 0);
0からスタートで読み取れる箇所ですので、こちらは定数化は不要そうですね！

2020-01-03 03:01 UTC, thisprodigiousgeek commented on www/conf/const.php
> +define('CHECK_ITEM_STOCK', 0);
0かどうかで読み取れる箇所ですので、こちらは定数化は不要そうですね！

2020-01-03 03:01 UTC, thisprodigiousgeek commented on www/conf/const.php
> +define('ADD_CART_ITEM', 1);
1件追加で読み取れる箇所ですので、こちらは定数化は不要そうですね！

2020-01-03 03:02 UTC, thisprodigiousgeek commented on www/conf/const.php
> +define('DELETE_COOKIE_TIME', 42000);
こちらは定数化すべき箇所ですね！変更の可能性も高い箇所です。素晴らしいです！

2020-01-03 03:02 UTC, thisprodigiousgeek commented on www/conf/const.php
> +define('COUNT_CHECK_NUMBER', 0);
0かどうかでチェックと読み取れる箇所ですので、こちらは定数化は不要そうですね！

2020-01-03 03:03 UTC, thisprodigiousgeek commented on www/conf/const.php
> +define('TOKEN_LENGTH', 20);
これは定数化がしっくりきますね！バッチリです！

2020-01-03 03:03 UTC, thisprodigiousgeek commented on www/conf/const.php
> +define('GET_TOKEN_START_NUMBER', 0);
0文字目からで読み取れる箇所ですので、こちらは定数化は不要そうですね！

2020-01-03 03:06 UTC, thisprodigiousgeek commented on www/conf/const.php
> +define('BASE_16', 16);
ここは微妙ですが、取得したランダムな文字列の基数を表す箇所なので、HASH_BASE_NUMなど、文字列の基数を表す数値だとわかりやすくしておくと良いでしょう。16が定数名に入ると、変更しづらくなってしまいますね！

2020-01-03 03:07 UTC, thisprodigiousgeek commented on www/conf/const.php
> +define('BASE_32', 32);
こちらはそもそも32ではなく36ですね！ここは後ほど詳しく解説します！

2020-01-03 03:08 UTC, thisprodigiousgeek commented on www/conf/const.php
> +define('SELECT_START_PAGE_NUMBER', 1);
こちらも-1ページで読み取れる箇所ですので、こちらは定数化は不要そうですね！

2020-01-03 03:08 UTC, thisprodigiousgeek requested changes
定数化のチャレンジ、素晴らしいですね！定数化が必要な箇所と不要な箇所がありましたので、コメントをチェックしてみてくださいね！

2020-01-03 06:59 UTC, takuya-lucky commented
確認いただきありがとうございました。
修正を致しましたので、再度確認をお願いいたします。

2020-01-04 00:04 UTC, takuya-lucky commented
昨日のレッスンを基にマジックナンバーの修正と一部変数名を変更しました。
確認をお願いいたします。

2020-01-04 00:21 UTC, thisprodigiousgeek commented on www/html/history.php
> +$current_page_behind_num = get_current_page_behind_num($num_purchase_histories);
startと対になるのがbehindでは不自然ですね！endなどの単語を利用しましょう！

2020-01-04 12:52 UTC, takuya-lucky commented
ご指摘いただきありがとうございました。
再度マジックナンバー及び変数名の変更を行いましたので、確認をお願いいたします。

2020-01-04 14:12 UTC, takuya-lucky commented
先ほどの変更に加えて、新たに変更点を見つけましたので、追加の変更を行いましたので、確認おwお願いいたします。

2020-01-05 00:38 UTC, thisprodigiousgeek commented on www/model/item.php
> +function sort_items($db, $is_open = true, $sort_item = 'new_item') {
ここは並び順を表す箇所なので、$sort_itemよりも、$order, あるいは$sort_orderなどがわかりやすそうですね！そのあとの$ordersとの整合性も取れる様になります。

2020-01-05 00:40 UTC, thisprodigiousgeek requested changes
ほぼ完成していますね！
あとは指摘部分を直して終了です。
また、ページネーションの前後ページの取得は
品質の面からはまだまだ色々と変更できるところです。こちらは別Issueでやってみましょう！

2020-01-05 01:05 UTC, thisprodigiousgeek approved these changes
はい、こちらでバッチリですね！マージさせていただきます！

2020-01-05 01:05 UTC, merged