SQLインジェクションの防止のためにバインド処理を行いました。
takuya-lucky/lamp_practice pull request #7
Opened 2019-11-29 14:24 UTC by takuya-lucky

SQLの脆弱性による書き換え等を防ぐために、以下のファイル・及び箇所をステートメントのバインド処理に書き換え致しました。
cart.php
- [ ] update_cart_amount
- [ ]  get_user_carts
- [ ]  get_user_cart
- [ ]  insert_cart
- [ ]  delete_cart
- [ ]  delete_user_carts

item.php
- [ ]  get_item
- [ ]  get_items
- [ ]  insert_item
- [ ]  update_item_status
- [ ]  update_item_stock
- [ ]  delete_item

user.php
- [ ] get_user
- [ ]  get_user_by_name
- [ ]  insert_user

2019-11-30 01:54 UTC, thisprodigiousgeek commented on www/model/functions.php
> +function input_check($int) {
functions.phpにis_positive_integerという関数がありますのでチェックしてみましょう！

2019-11-30 02:01 UTC, thisprodigiousgeek requested changes
バリデーション用関数についてはコメントをチェックしてみましょう！
また、バリデーション用の関数が利用されている箇所が無いようですが、
こちらはコミット漏れでしょうか。
バインドの箇所はバッチリですので、残りわずか、しっかり仕上げていきましょう！

2019-11-30 04:40 UTC, takuya-lucky commented
ご指摘いただきましたバリデーションの追加を行いましたので、確認をお願いいたします。
また、コードリーディングの練習の為に、コメントを追加してありますので、そちらの更新もありますので、ご容赦いただきますようお願いします。

2019-12-01 00:34 UTC, thisprodigiousgeek requested changes
まずはバリデーションの実行部分を追加していただけましたね！
現状
* バリデーションに通っていない値でもSQLが実行されてしまう
* is_positive_integerが利用されていない
といった問題点が見受けられますのでこれらについてレッスンで確認していきましょう！

2019-12-01 02:27 UTC, takuya-lucky commented
バリデーションの処理を変更いたしました。
そして、不要になったユーザー定義関数input_checkも削除いたしました。
確認をお願いします。

2019-12-01 17:17 UTC, thisprodigiousgeek approved these changes
はい、こちらでバッチリですね！コメントでコードリーディングも進めていただけていて素晴らしいです。マージさせていただきます！

2019-12-01 17:17 UTC, merged